package pojos;
// Generated 27-may-2021 19:55:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private String nombre;
     private Partidos partidos;
     private String nomCorto;
     private Set jugadoses = new HashSet(0);
     private Set integrantes = new HashSet(0);

    public Equipo() {
    }

	
    public Equipo(String nombre, Partidos partidos, String nomCorto) {
        this.nombre = nombre;
        this.partidos = partidos;
        this.nomCorto = nomCorto;
    }
    public Equipo(String nombre, Partidos partidos, String nomCorto, Set jugadoses, Set integrantes) {
       this.nombre = nombre;
       this.partidos = partidos;
       this.nomCorto = nomCorto;
       this.jugadoses = jugadoses;
       this.integrantes = integrantes;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Partidos getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Partidos partidos) {
        this.partidos = partidos;
    }
    public String getNomCorto() {
        return this.nomCorto;
    }
    
    public void setNomCorto(String nomCorto) {
        this.nomCorto = nomCorto;
    }
    public Set getJugadoses() {
        return this.jugadoses;
    }
    
    public void setJugadoses(Set jugadoses) {
        this.jugadoses = jugadoses;
    }
    public Set getIntegrantes() {
        return this.integrantes;
    }
    
    public void setIntegrantes(Set integrantes) {
        this.integrantes = integrantes;
    }




}


