package pojos;
// Generated 27-may-2021 19:55:39 by Hibernate Tools 4.3.1



/**
 * Estadisticas generated by hbm2java
 */
public class Estadisticas  implements java.io.Serializable {


     private Integer id;
     private Partidos partidos;
     private int golesTot;
     private int tirosPuerta;
     private int amarillas;
     private int rojas;
     private int azules;
     private String ganadorEdc;

    public Estadisticas() {
    }

    public Estadisticas(Partidos partidos, int golesTot, int tirosPuerta, int amarillas, int rojas, int azules, String ganadorEdc) {
       this.partidos = partidos;
       this.golesTot = golesTot;
       this.tirosPuerta = tirosPuerta;
       this.amarillas = amarillas;
       this.rojas = rojas;
       this.azules = azules;
       this.ganadorEdc = ganadorEdc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Partidos getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Partidos partidos) {
        this.partidos = partidos;
    }
    public int getGolesTot() {
        return this.golesTot;
    }
    
    public void setGolesTot(int golesTot) {
        this.golesTot = golesTot;
    }
    public int getTirosPuerta() {
        return this.tirosPuerta;
    }
    
    public void setTirosPuerta(int tirosPuerta) {
        this.tirosPuerta = tirosPuerta;
    }
    public int getAmarillas() {
        return this.amarillas;
    }
    
    public void setAmarillas(int amarillas) {
        this.amarillas = amarillas;
    }
    public int getRojas() {
        return this.rojas;
    }
    
    public void setRojas(int rojas) {
        this.rojas = rojas;
    }
    public int getAzules() {
        return this.azules;
    }
    
    public void setAzules(int azules) {
        this.azules = azules;
    }
    public String getGanadorEdc() {
        return this.ganadorEdc;
    }
    
    public void setGanadorEdc(String ganadorEdc) {
        this.ganadorEdc = ganadorEdc;
    }




}


