package pojos;
// Generated 24-may-2021 18:33:00 by Hibernate Tools 4.3.1



/**
 * Gestiona generated by hbm2java
 */
public class Gestiona  implements java.io.Serializable {


     private GestionaId id;
     private Partidos partidos;
     private Usuario usuario;

    public Gestiona() {
    }

    public Gestiona(GestionaId id, Partidos partidos, Usuario usuario) {
       this.id = id;
       this.partidos = partidos;
       this.usuario = usuario;
    }
   
    public GestionaId getId() {
        return this.id;
    }
    
    public void setId(GestionaId id) {
        this.id = id;
    }
    public Partidos getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Partidos partidos) {
        this.partidos = partidos;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


