package pojos;
// Generated 04-may-2021 16:30:55 by Hibernate Tools 4.3.1



/**
 * GestionaId generated by hbm2java
 */
public class GestionaId  implements java.io.Serializable {


     private String nick;
     private int idPartido;

    public GestionaId() {
    }

    public GestionaId(String nick, int idPartido) {
       this.nick = nick;
       this.idPartido = idPartido;
    }
   
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public int getIdPartido() {
        return this.idPartido;
    }
    
    public void setIdPartido(int idPartido) {
        this.idPartido = idPartido;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GestionaId) ) return false;
		 GestionaId castOther = ( GestionaId ) other; 
         
		 return ( (this.getNick()==castOther.getNick()) || ( this.getNick()!=null && castOther.getNick()!=null && this.getNick().equals(castOther.getNick()) ) )
 && (this.getIdPartido()==castOther.getIdPartido());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNick() == null ? 0 : this.getNick().hashCode() );
         result = 37 * result + this.getIdPartido();
         return result;
   }   


}


