package pojos;
// Generated 02-jun-2021 17:56:08 by Hibernate Tools 4.3.1



/**
 * Integrante generated by hbm2java
 */
public class Integrante  implements java.io.Serializable {


     private String dni;
     private Equipo equipo;
     private String nombre;
     private String apellidos;
     private int dorsal;

    public Integrante() {
    }

    public Integrante(String dni, Equipo equipo, String nombre, String apellidos, int dorsal) {
       this.dni = dni;
       this.equipo = equipo;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.dorsal = dorsal;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getDorsal() {
        return this.dorsal;
    }
    
    public void setDorsal(int dorsal) {
        this.dorsal = dorsal;
    }




}


