package pojos;
// Generated 24-may-2021 18:33:00 by Hibernate Tools 4.3.1



/**
 * JueganId generated by hbm2java
 */
public class JueganId  implements java.io.Serializable {


     private int idPartido;
     private int idInstalacion;

    public JueganId() {
    }

    public JueganId(int idPartido, int idInstalacion) {
       this.idPartido = idPartido;
       this.idInstalacion = idInstalacion;
    }
   
    public int getIdPartido() {
        return this.idPartido;
    }
    
    public void setIdPartido(int idPartido) {
        this.idPartido = idPartido;
    }
    public int getIdInstalacion() {
        return this.idInstalacion;
    }
    
    public void setIdInstalacion(int idInstalacion) {
        this.idInstalacion = idInstalacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JueganId) ) return false;
		 JueganId castOther = ( JueganId ) other; 
         
		 return (this.getIdPartido()==castOther.getIdPartido())
 && (this.getIdInstalacion()==castOther.getIdInstalacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPartido();
         result = 37 * result + this.getIdInstalacion();
         return result;
   }   


}


