package pojos;
// Generated 27-may-2021 19:55:39 by Hibernate Tools 4.3.1



/**
 * Jugados generated by hbm2java
 */
public class Jugados  implements java.io.Serializable {


     private int idPartido;
     private Equipo equipo;
     private Partidos partidos;

    public Jugados() {
    }

	
    public Jugados(int idPartido, Equipo equipo) {
        this.idPartido = idPartido;
        this.equipo = equipo;
    }
    public Jugados(int idPartido, Equipo equipo, Partidos partidos) {
       this.idPartido = idPartido;
       this.equipo = equipo;
       this.partidos = partidos;
    }
   
    public int getIdPartido() {
        return this.idPartido;
    }
    
    public void setIdPartido(int idPartido) {
        this.idPartido = idPartido;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Partidos getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Partidos partidos) {
        this.partidos = partidos;
    }




}


