package pojos;
// Generated 04-jun-2021 20:24:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidos generated by hbm2java
 */
public class Partidos  implements java.io.Serializable {


     private Integer idPartido;
     private String local;
     private String visitante;
     private String resultado;
     private Date fecha;
     private Set estadisticases = new HashSet(0);
     private Set jugadoses = new HashSet(0);
     private Set juegans = new HashSet(0);

    public Partidos() {
    }

	
    public Partidos(String local, String visitante, String resultado, Date fecha) {
        this.local = local;
        this.visitante = visitante;
        this.resultado = resultado;
        this.fecha = fecha;
    }
    public Partidos(String local, String visitante, String resultado, Date fecha, Set estadisticases, Set jugadoses, Set juegans) {
       this.local = local;
       this.visitante = visitante;
       this.resultado = resultado;
       this.fecha = fecha;
       this.estadisticases = estadisticases;
       this.jugadoses = jugadoses;
       this.juegans = juegans;
    }
   
    public Integer getIdPartido() {
        return this.idPartido;
    }
    
    public void setIdPartido(Integer idPartido) {
        this.idPartido = idPartido;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getVisitante() {
        return this.visitante;
    }
    
    public void setVisitante(String visitante) {
        this.visitante = visitante;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getEstadisticases() {
        return this.estadisticases;
    }
    
    public void setEstadisticases(Set estadisticases) {
        this.estadisticases = estadisticases;
    }
    public Set getJugadoses() {
        return this.jugadoses;
    }
    
    public void setJugadoses(Set jugadoses) {
        this.jugadoses = jugadoses;
    }
    public Set getJuegans() {
        return this.juegans;
    }
    
    public void setJuegans(Set juegans) {
        this.juegans = juegans;
    }




}


