package pojos;
// Generated 24-may-2021 18:33:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidos generated by hbm2java
 */
public class Partidos  implements java.io.Serializable {


     private Integer id;
     private String resultado;
     private Date fecha;
     private Set estadisticases = new HashSet(0);
     private Set equipos = new HashSet(0);
     private Set gestionas = new HashSet(0);
     private Set juegans = new HashSet(0);

    public Partidos() {
    }

	
    public Partidos(String resultado, Date fecha) {
        this.resultado = resultado;
        this.fecha = fecha;
    }
    public Partidos(String resultado, Date fecha, Set estadisticases, Set equipos, Set gestionas, Set juegans) {
       this.resultado = resultado;
       this.fecha = fecha;
       this.estadisticases = estadisticases;
       this.equipos = equipos;
       this.gestionas = gestionas;
       this.juegans = juegans;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getEstadisticases() {
        return this.estadisticases;
    }
    
    public void setEstadisticases(Set estadisticases) {
        this.estadisticases = estadisticases;
    }
    public Set getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set equipos) {
        this.equipos = equipos;
    }
    public Set getGestionas() {
        return this.gestionas;
    }
    
    public void setGestionas(Set gestionas) {
        this.gestionas = gestionas;
    }
    public Set getJuegans() {
        return this.juegans;
    }
    
    public void setJuegans(Set juegans) {
        this.juegans = juegans;
    }




}


