package pojos;
// Generated 27-may-2021 19:55:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidos generated by hbm2java
 */
public class Partidos  implements java.io.Serializable {


     private Integer id;
     private Jugados jugados;
     private String resultado;
     private Date fecha;
     private Set estadisticases = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set equipos = new HashSet(0);
     private Set juegans = new HashSet(0);

    public Partidos() {
    }

	
    public Partidos(Jugados jugados, String resultado, Date fecha) {
        this.jugados = jugados;
        this.resultado = resultado;
        this.fecha = fecha;
    }
    public Partidos(Jugados jugados, String resultado, Date fecha, Set estadisticases, Set usuarios, Set equipos, Set juegans) {
       this.jugados = jugados;
       this.resultado = resultado;
       this.fecha = fecha;
       this.estadisticases = estadisticases;
       this.usuarios = usuarios;
       this.equipos = equipos;
       this.juegans = juegans;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Jugados getJugados() {
        return this.jugados;
    }
    
    public void setJugados(Jugados jugados) {
        this.jugados = jugados;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getEstadisticases() {
        return this.estadisticases;
    }
    
    public void setEstadisticases(Set estadisticases) {
        this.estadisticases = estadisticases;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set equipos) {
        this.equipos = equipos;
    }
    public Set getJuegans() {
        return this.juegans;
    }
    
    public void setJuegans(Set juegans) {
        this.juegans = juegans;
    }




}


