package pojos;
// Generated 04-jun-2021 20:24:08 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nick;
     private String nombre;
     private String password;
     private String rol;

    public Usuario() {
    }

    public Usuario(String nick, String nombre, String password, String rol) {
       this.nick = nick;
       this.nombre = nombre;
       this.password = password;
       this.rol = rol;
    }
   
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }




}


