package pojos;
// Generated 04-jun-2021 20:24:08 by Hibernate Tools 4.3.1



/**
 * Estadisticas generated by hbm2java
 */
public class Estadisticas  implements java.io.Serializable {


     private Integer id;
     private Partidos partidos;
     private String golesTot;
     private String tirosPuerta;
     private String amarillas;
     private String rojas;
     private String azules;

    public Estadisticas() {
    }

    public Estadisticas(Partidos partidos, String golesTot, String tirosPuerta, String amarillas, String rojas, String azules) {
       this.partidos = partidos;
       this.golesTot = golesTot;
       this.tirosPuerta = tirosPuerta;
       this.amarillas = amarillas;
       this.rojas = rojas;
       this.azules = azules;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Partidos getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Partidos partidos) {
        this.partidos = partidos;
    }
    public String getGolesTot() {
        return this.golesTot;
    }
    
    public void setGolesTot(String golesTot) {
        this.golesTot = golesTot;
    }
    public String getTirosPuerta() {
        return this.tirosPuerta;
    }
    
    public void setTirosPuerta(String tirosPuerta) {
        this.tirosPuerta = tirosPuerta;
    }
    public String getAmarillas() {
        return this.amarillas;
    }
    
    public void setAmarillas(String amarillas) {
        this.amarillas = amarillas;
    }
    public String getRojas() {
        return this.rojas;
    }
    
    public void setRojas(String rojas) {
        this.rojas = rojas;
    }
    public String getAzules() {
        return this.azules;
    }
    
    public void setAzules(String azules) {
        this.azules = azules;
    }




}


