package pojos;
// Generated 04-jun-2021 20:24:08 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Instalaciones generated by hbm2java
 */
public class Instalaciones implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private String direccion;
    private String ciudad;
    private String longitud;
    private String latitud;
    private int capacidad;
    private Set juegans = new HashSet(0);

    public Instalaciones() {
    }

    
    public Instalaciones(String nombre, String direccion, String ciudad, int capacidad) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.capacidad = capacidad;
    }

    public Instalaciones(String nombre, String direccion, String ciudad, String longitud, String latitud, int capacidad) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.longitud = longitud;
        this.latitud = latitud;
        this.capacidad = capacidad;
    }

    public Instalaciones(String nombre, String direccion, String ciudad, int capacidad, Set juegans) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.capacidad = capacidad;
        this.juegans = juegans;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getCiudad() {
        return ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    public String getLongitud() {
        return longitud;
    }

    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    public String getLatitud() {
        return latitud;
    }

    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    public int getCapacidad() {
        return this.capacidad;
    }

    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }

    public Set getJuegans() {
        return this.juegans;
    }

    public void setJuegans(Set juegans) {
        this.juegans = juegans;
    }

    public String toString() {
        return this.nombre;
    }

}
